### ISSUE TITLE
No module named utils

### ISSUE THREAD

**Issue by bets90** [eon01/DoMonit#2]
`python examples.py` results in:

`Traceback (most recent call last):
  File "/dockermonitor/DoMonit/DoMonit/examples.py", line 9, in <module>
    from domonit.changes import Changes
  File "/dockermonitor/DoMonit/DoMonit/domonit/changes.py", line 6, in <module>
    from utils.utils import Utils
ImportError: No module named utils`

**Comment by bets90** [comment]
utils folder needs an __init__.py

**Comment by eon01** [comment]
I added the init.py to the folder ! Thank you @bets90 !
